Develop
mobie/mobie-io pull request #30
Opened 2021-09-13 13:02 UTC by KateMoreva

2021-09-13 13:07 UTC, tischi requested changes

2021-09-13 13:07 UTC, tischi commented on src/main/java/org/embl/mobie/viewer/Main.java
> +package org.embl.mobie.viewer;
@KateMoreva  this should be `org.embl.mobie.io` (not `viewer`).

2021-09-13 13:19 UTC, tischi approved these changes
Perfect as far as I can see!
Thanks!

2021-09-13 15:43 UTC, KateMoreva commented
> Perfect as far as I can see!
> Thanks!


@tischi, somehow I cannot rename this repo, could you please change the name to the `mobie-io`?

2021-09-14 07:40 UTC, tischi commented
I renamed it.

2021-09-14 07:44 UTC, merged